# Generated by Django 4.1.6 on 2023-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menu_delete_comment_remove_post_category_delete_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
            ],
        ),
    ]
